import type { MachineItem } from "./types";

export const machinesMock: MachineItem[] = [
  {
    id: 1,
    machine: "Dryer-3F-L3 301호",
    type: "dryer",
    status: "사용중",
    deviceStatus: "건조중",
    remain: "00:32:12",
  },
  {
    id: 2,
    machine: "Dryer-3F-L3 301호",
    type: "dryer",
    status: "사용중",
    deviceStatus: "건조중",
    remain: "00:32:12",
  },
  {
    id: 3,
    machine: "Dryer-3F-L3",
    type: "dryer",
    status: "미사용",
  },
  {
    id: 4,
    machine: "Dryer-3F-L3 301호",
    type: "dryer",
    status: "사용중",
    deviceStatus: "건조중",
    remain: "00:32:12",
  },
  {
    id: 5,
    machine: "Dryer-3F-L3 301호",
    type: "dryer",
    status: "사용 정지",
    deviceStatus: "건조중",
    remain: "00:32:12",
  },
  {
    id: 6,
    machine: "Dryer-3F-L3 301호",
    type: "dryer",
    status: "예약",
    reserveAt: "25.8.18 21:35",
  },
  {
    id: 7,
    machine: "Washer-3F-L1 301호",
    type: "washer",
    status: "확인필요",
  },
  {
    id: 8,
    machine: "Washer-3F-L1 301호",
    type: "washer",
    status: "고장",
  },
  {
    id: 9,
    machine: "Washer-3F-L1 301호",
    type: "washer",
    status: "사용중",
    deviceStatus: "건조중",
    remain: "00:32:12",
  },
  {
    id: 10,
    machine: "Washer-3F-L1",
    type: "washer",
    status: "미사용",
  },
  {
    id: 11,
    machine: "Washer-3F-L1 301호",
    type: "washer",
    status: "사용 정지",
    deviceStatus: "건조중",
    remain: "00:32:12",
  },
  {
    id: 12,
    machine: "Washer-3F-L1 301호",
    type: "washer",
    status: "예약",
    reserveAt: "25.8.18 21:35",
  },
];